# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('tenant', 'Tenant')], help_text="Explicit delivery target type. NEVER null. 'user'   → channel group: user:{target_id} 'tenant' → channel group: tenant:{target_id} Tenant-wide events require explicit authorization at dispatch time.", max_length=20)),
                ('target_id', models.CharField(help_text="The target identifier. For target_type='user': the User UUID string. For target_type='tenant': the FreeSWITCH tenant UUID string.", max_length=255)),
                ('event_type', models.CharField(help_text="Normalized application event type (e.g. 'call.incoming', 'extension.updated', 'fax.received'). NOT the raw FreeSWITCH event name.", max_length=100)),
                ('payload', models.JSONField(help_text='Normalized event payload to be sent to the WebSocket client. Must conform to the application event schema. SECURITY: Must NOT contain SIP passwords, API keys, application passwords, or raw FreeSWITCH webhook payloads.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this event was created.')),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='UTC timestamp when this event was successfully published to Redis.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Delivery status of this outbox event.', max_length=20)),
                ('tenant', models.ForeignKey(help_text='The tenant context for this event.', on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_outbox_status_created'), models.Index(fields=['status', 'tenant'], name='idx_outbox_status_tenant'), models.Index(fields=['target_type', 'target_id', 'status'], name='idx_outbox_target_status')],
            },
        ),
    ]
