# Generated by Django 6.1 on 2026-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outboxevent',
            name='idx_outbox_status_created',
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='idx_outbox_pending_created'),
        ),
    ]
