# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('freeswitch_object_id', models.CharField(help_text='The object_id assigned by FreeSWITCH to this DID. Unique within a tenant — not globally unique.', max_length=255)),
                ('number', models.CharField(help_text="Phone number in E.164 format (e.g. '+18321234567'). Stored as provided by FreeSWITCH.", max_length=20)),
                ('calling_enabled', models.BooleanField(default=False, help_text='This DID can be used for voice calling.')),
                ('messaging_enabled', models.BooleanField(default=False, help_text='This DID can be used for SMS/MMS messaging.')),
                ('tenant', models.ForeignKey(help_text='The tenant that OWNS this phone number.', on_delete=django.db.models.deletion.PROTECT, related_name='dids', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'DID',
                'verbose_name_plural': 'DIDs',
                'db_table': 'dids',
                'ordering': ['tenant', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UserDID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('did', models.ForeignKey(help_text='The DID the user is being granted access to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_dids', to='dids.did')),
            ],
            options={
                'verbose_name': 'User DID Assignment',
                'verbose_name_plural': 'User DID Assignments',
                'db_table': 'user_dids',
            },
        ),
    ]
