# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdid',
            name='user',
            field=models.ForeignKey(help_text='The user being granted access to this DID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_dids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='did',
            index=models.Index(fields=['tenant', 'number'], name='idx_did_tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='did',
            constraint=models.UniqueConstraint(fields=('tenant', 'freeswitch_object_id'), name='uq_did_tenant_object_id'),
        ),
        migrations.AddIndex(
            model_name='userdid',
            index=models.Index(fields=['user'], name='idx_userdid_user'),
        ),
        migrations.AddIndex(
            model_name='userdid',
            index=models.Index(fields=['did'], name='idx_userdid_did'),
        ),
        migrations.AddConstraint(
            model_name='userdid',
            constraint=models.UniqueConstraint(fields=('user', 'did'), name='uq_user_did_assignment'),
        ),
    ]
