# Generated by Django 6.1 on 2026-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='number',
            field=models.CharField(db_index=True, help_text="Phone number in E.164 format (e.g. '+18321234567'). Stored as provided by FreeSWITCH.", max_length=20),
        ),
    ]
