# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('freeswitch_object_id', models.CharField(help_text='The object_id assigned by FreeSWITCH to this extension. Unique within a tenant. Not globally unique.', max_length=255)),
                ('extension_number', models.CharField(help_text="The dialable extension number (e.g. '101'). Unique within a tenant — not globally unique. Tenant A and Tenant B may both have extension '101'.", max_length=20)),
                ('sip_username', models.CharField(help_text="SIP username used for registration (e.g. '101-HVA'). This is the telephony identity, separate from the application email.", max_length=255)),
                ('encrypted_sip_password', models.TextField(help_text='SecretService-encrypted SIP password. SECURITY: Decrypt only in-memory via SecretService.decrypt(). Never log, serialize in standard APIs, or include in WebSocket events. When credentials change, emit sip.credentials.updated with {requires_refresh: true} only — never the actual password.')),
                ('sip_server', models.CharField(help_text="SIP registrar / proxy hostname or IP address (e.g. 'sip.example.com' or '192.168.1.1'). Required for SIP client registration.", max_length=255)),
                ('transport_type', models.CharField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('TLS', 'TLS'), ('DTLS', 'DTLS')], default='UDP', help_text='SIP transport protocol. One of: UDP, TCP, TLS, DTLS. Required for SIP client registration.', max_length=10)),
                ('tenant', models.ForeignKey(help_text='The tenant this extension belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Extension',
                'verbose_name_plural': 'Extensions',
                'db_table': 'extensions',
                'ordering': ['tenant', 'extension_number'],
            },
        ),
    ]
