# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The User currently assigned to this extension. Nullable — an extension may exist unassigned. Assignment/unassignment is handled by ExtensionService to ensure atomicity and proper notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='extension',
            index=models.Index(fields=['tenant', 'extension_number'], name='idx_extension_tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('tenant', 'freeswitch_object_id'), name='uq_extension_tenant_object_id'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('tenant', 'extension_number'), name='uq_extension_tenant_number'),
        ),
    ]
