# Generated by Django 6.1 on 2026-08-28 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='extension',
            name='idx_extension_tenant_number',
        ),
        migrations.AddIndex(
            model_name='extension',
            index=models.Index(fields=['tenant', 'sip_username'], name='idx_ext_tenant_sipuser'),
        ),
    ]
