# Generated by Django 6.1 on 2026-08-28 19:50

import apps.tenants.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('freeswitch_tenant_uuid', models.UUIDField(db_index=True, help_text='The stable UUID assigned by FreeSWITCH to this tenant. Used as the canonical external reference across the system. This value must never change after creation.', unique=True)),
                ('tenant_code', models.CharField(db_index=True, help_text="Short mnemonic code for this tenant (e.g. 'HVA', 'GMD'). This value can change. Never use it as a FK or URL identifier.", max_length=50)),
                ('tenant_name', models.CharField(help_text='Human-readable display name for this tenant.', max_length=255)),
                ('encrypted_api_key', models.TextField(help_text='SecretService-encrypted FreeSWITCH API key for this tenant. This is per-tenant — there is no shared global key. SECURITY: Decrypt only in-memory via SecretService.decrypt(). Never log, serialize, or return the plaintext value.')),
                ('features', models.JSONField(default=apps.tenants.models.default_tenant_features, help_text='Dict of enabled features for this tenant. Valid keys: calling, messaging, fax, voicemail. Values must be booleans. Example: {"calling": true, "messaging": true, "fax": false, "voicemail": true}', validators=[apps.tenants.models.validate_tenant_features])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive tenants are disabled system-wide.')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['tenant_name'],
            },
        ),
    ]
