# Generated by Django 6.1 on 2026-08-28 19:50

import apps.webhooks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('provider', models.CharField(default='freeswitch', help_text="Source of this webhook (e.g. 'freeswitch').", max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text="The event type as sent by FreeSWITCH (e.g. 'extension.created', 'call.incoming').", max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='The FreeSWITCH object_id of the affected resource, if applicable. Used for idempotency checks and ordering logic.', max_length=255, null=True)),
                ('tenant_id', models.CharField(db_index=True, help_text='FreeSWITCH tenant UUID string from the webhook payload.', max_length=255)),
                ('tenant_code', models.CharField(blank=True, help_text='FreeSWITCH tenant_code from the webhook payload (informational).', max_length=50)),
                ('provider_timestamp', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the event as reported by FreeSWITCH. Used for ordering/stale-event detection.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when Django received this webhook.')),
                ('payload', models.JSONField(help_text="The sanitized webhook payload. Sensitive fields (api_key, password, etc.) are replaced with '[REDACTED]' before this record is written. The unsanitized payload is never persisted.")),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing state of this webhook event.', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='UTC timestamp when processing completed (success or final failure).', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if processing failed. Never contains secrets.', null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.webhooks.models._default_expires_at, help_text='UTC expiry timestamp (received_at + 48h). Celery periodic task deletes records where expires_at < now(). This index is critical for cleanup query performance.')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'object_id', 'provider_timestamp'], name='idx_webhooklog_idempotency'), models.Index(fields=['processing_status', 'expires_at'], name='idx_webhooklog_status_expiry'), models.Index(fields=['tenant_id', 'event_type', 'received_at'], name='idx_webhooklog_tenant_event')],
            },
        ),
    ]
