# Generated by Django 6.1 on 2026-08-28 19:50

import apps.users.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Application login email. Globally unique across ALL tenants — two tenants cannot share an email. Stored in lowercase, stripped of whitespace (enforced by UserManager). This is the application identity; SIP username lives on Extension.', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('user', 'User')], db_index=True, default='user', help_text='Primary role. NOT the complete authorization system — permissions are first-class. superadmin: platform-level admin + communication user of own tenant. admin: tenant-scoped admin. user: normal user.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive users cannot authenticate. Disabling a User does NOT automatically delete their FreeSWITCH extension. Application user lifecycle and FreeSWITCH resource lifecycle are separate.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('fax_boxes', models.JSONField(blank=True, default=list, help_text='List of FaxBox assignments. Structure: [{"fax_uuid": str, "fax_caller_id_name": str, "fax_caller_id_number": str}, ...]. Multiple users may share the same fax_uuid. WRITE ONLY via FaxBoxService — direct assignment bypasses FreeSWITCH tenant ownership verification.', validators=[apps.users.validators.validate_fax_boxes])),
                ('voicemail_boxes', models.JSONField(blank=True, default=list, help_text='List of voicemail box IDs this user has access to. Structure: [int, ...]. Multiple users may share the same voicemail_box_id. WRITE ONLY via VoicemailBoxService — direct assignment bypasses FreeSWITCH tenant ownership verification.', validators=[apps.users.validators.validate_voicemail_boxes])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(help_text='The tenant this user belongs to. Mandatory. For superadmins: this determines their communication scope (CDR, voicemail, fax, calling). Platform-administration scope is governed separately by permissions.', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['tenant', 'role'], name='idx_user_tenant_role'), models.Index(fields=['tenant', 'is_active'], name='idx_user_tenant_active')],
            },
        ),
    ]
