# Generated by Django 6.1 on 2026-08-28 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicemailReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('voicemail_box_id', models.PositiveIntegerField(db_index=True, help_text='The voicemail box ID (integer) that received this message. Must be present in user.voicemail_boxes at time of access. Matches the integer values stored in User.voicemail_boxes JSON.')),
                ('voicemail_message_id', models.CharField(help_text='The FreeSWITCH-assigned UUID for this specific voicemail message. Used to identify the message within the voicemail box.', max_length=255)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp when this user marked the message as read.')),
                ('user', models.ForeignKey(help_text='The user who has read this voicemail message.', on_delete=django.db.models.deletion.CASCADE, related_name='voicemail_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voicemail Read State',
                'verbose_name_plural': 'Voicemail Read States',
                'db_table': 'voicemail_read_states',
                'indexes': [models.Index(fields=['user', 'voicemail_box_id'], name='idx_vmread_user_box'), models.Index(fields=['voicemail_box_id', 'voicemail_message_id'], name='idx_vmread_box_message')],
                'constraints': [models.UniqueConstraint(fields=('user', 'voicemail_box_id', 'voicemail_message_id'), name='uq_voicemail_read_state')],
            },
        ),
    ]
