# Generated by Django 6.1 on 2026-08-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicemail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voicemailreadstate',
            name='idx_vmread_user_box',
        ),
        migrations.RemoveIndex(
            model_name='voicemailreadstate',
            name='idx_vmread_box_message',
        ),
        migrations.RemoveConstraint(
            model_name='voicemailreadstate',
            name='uq_voicemail_read_state',
        ),
        migrations.DeleteModel(
            name='VoicemailReadState',
        ),
    ]
