# Generated by Django 6.1 on 2026-08-28 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Action identifier (e.g. 'user.created', 'did.assigned'). Use AuditAction constants — do not use raw strings.", max_length=100)),
                ('target_type', models.CharField(help_text="Type of the resource this action was performed on (e.g. 'User', 'Extension', 'DID', 'Tenant').", max_length=100)),
                ('target_id', models.CharField(help_text='UUID or identifier of the affected resource.', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Sanitized contextual details about the action. SECURITY: Must never contain passwords, SIP credentials, API keys, or any other secrets. Example: {"old_role": "user", "new_role": "admin"}')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor if the action was HTTP-initiated.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of this audit entry. Append-only.')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
